version: 2
jobs:
  build:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: Export Site
          command: yarn export
      - persist_to_workspace:
          root: __sapper__
          paths:
            - export
  publish:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Install Dependencies & Configure Environment
          command: |
            echo 'export PATH=$(yarn global bin):$PATH' >> $BASH_ENV
            source $BASH_ENV
            yarn global add gh-pages
            git config user.email "noreply@nellexchange.github.io"
            git config user.name "ci-build"
      - add_ssh_keys:
          fingerprints:
            - "e1:c9:94:fa:7a:a0:08:7a:fc:94:41:74:07:3a:f4:81"
      - run:
          name: Deploy Site
          command: gh-pages -r git@github.com:NELLExchange/NELLExchange.github.io.git --branch master --message "[skip ci] Publish" --dist export
workflows:
  version: 2
  build:
    jobs:
      - build
      - publish:
          requires:
            - build
          filters:
            branches:
              only: master
