version: 2
jobs:
  build:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: Build Site
          command: yarn build
      - persist_to_workspace:
          root: .
          paths:
            - public
  publish:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Install Dependencies & Configure Environment
          command: |
            echo 'export PATH=$(yarn global bin):$PATH' >> $BASH_ENV
            source $BASH_ENV
            yarn global add gh-pages
            git config user.email "noreply@nelle.no"
            git config user.name "ci-build"
      - add_ssh_keys:
          fingerprints:
            - "df:e5:5d:96:b2:5b:0c:48:a6:1d:15:6b:ec:d9:b8:37"
      - run:
          name: Deploy Site
          command: gh-pages --message "[skip ci] Publish" --dist public
workflows:
  version: 2
  build:
    jobs:
      - build
      - publish:
          requires:
            - build
          filters:
            branches:
              only: master
